########################
# Author: Mengjuei Hsieh
# License: Public Domain
########################
# This is the config file for building h5r dependencies with Travis-ci.org

language: cpp

compiler:
  - gcc

before_install:
#  - cat /etc/apt/sources.list
#  - ls -al /etc/apt/sources.list.d
#  - lsb_release -a
  - sudo apt-get update -qq
  - sudo apt-get install binutils-mingw-w64-x86-64
  - sudo apt-get install binutils-mingw-w64-i686
  - sudo apt-get install gcc-mingw-w64-x86-64
  - sudo apt-get install gcc-mingw-w64-i686
  - sudo apt-get install g++-mingw-w64-x86-64
  - sudo apt-get install g++-mingw-w64-i686
  - sudo apt-get install gfortran-mingw-w64-x86-64
  - sudo apt-get install gfortran-mingw-w64-i686
  - sudo apt-get install mingw-w64
  - sudo apt-get install mingw-w64-dev
  - sudo apt-get install -qq -y wine

install:
# borrowed from gdal_coverage
  - ln -s /usr/lib/gcc/x86_64-w64-mingw32/4.6/libstdc++-6.dll  $HOME/.wine/drive_c/windows
  - ln -s /usr/lib/gcc/x86_64-w64-mingw32/4.6/libgcc_s_sjlj-1.dll  $HOME/.wine/drive_c/windows
# fetch zlib, szlib, and hdf5
  - curl -O http://zlib.net/zlib-1.2.8.tar.gz
  - tar zxvf zlib-1.2.8.tar.gz
  - curl -O http://www.hdfgroup.org/ftp/lib-external/szip/2.1/src/szip-2.1.tar.gz
  - tar zxvf szip-2.1.tar.gz
  - curl -O http://www.hdfgroup.org/ftp/HDF5/current/src/hdf5-1.8.13.tar.gz
  - tar zxvf hdf5-1.8.13.tar.gz
  - "patch -p0 < hdf5-1.8.13.patch"

script:
  - "echo 'success!'"

#notifications:
#  email:
#    recipients:
#      - mhsieh@pacificbiosciences.com
#
#  irc:
#    channels:
#      - "irc.freenode.org#osxchat"
#    use_notice: true
#    on_success: change
